### ISSUE TITLE
Export-BypassBlock, I get the error "The term 'Export-BypassBlock' is not recognized as the name of a cmdlet"

### ISSUE THREAD

**Issue by l4m3us3r** [AdamGrossTX/FU.WhyAmIBlocked#20]
Hi,

After I run Get-FUBlocks on a local device (and it finds a block) and I try Export-BypassBlock, I get the error "The term 'Export-BypassBlock' is not recognized as the name of a cmdlet"

Am I doing something wrong?

(I am testing on a 1903 machine that has a upgrade block from Trend AV.  My aim is to figure out the registry bypass so that the 20 x 1903 machines for this client will upgrade)

**Comment by AdamGrossTX** [comment]
Try importing the module.

**Comment by l4m3us3r** [comment]
okay, the command seems to be export-FUbypassblock, the doco has it as export-bypassblock:
PS C:\Windows\system32> Export-FUBypassBlock
 + Finding and exporting block bypass.. √
PS C:\Windows\system32> Export-BypassBlock
Export-BypassBlock : The term 'Export-BypassBlock' is not recognized as the name of a cmdlet
