### ISSUE TITLE
where/what format do bypass files come out?

### ISSUE THREAD

**Issue by l4m3us3r** [AdamGrossTX/FU.WhyAmIBlocked#21]
where/what format do bypass files come out?

The script output is below, but I can't seem to generate/find the bypassblocker remediation files.

 ++ Finding block entries in C:\FeatureUpdateBlocks\MJ-MJD82PRJSISQ_20211004_094943\AppCompatAppraiser_Appraiser_AlternateData_appraiser.sdb_ver_2507.XML..
 ++No Matches Found in C:\FeatureUpdateBlocks\MJ-MJD82PRJSISQ_20211004_094943\AppCompatAppraiser_Appraiser_AlternateData_appraiser.sdb_ver_2507.XML.
 ++ Finding block entries in C:\FeatureUpdateBlocks\MJ-MJD82PRJSISQ_20211004_094943\System32Appraiser_System32Appraiser_appraiser.sdb_ver_2450.XML..
 ++No Matches Found in C:\FeatureUpdateBlocks\MJ-MJD82PRJSISQ_20211004_094943\System32Appraiser_System32Appraiser_appraiser.sdb_ver_2450.XML.
 + Finding and exporting block bypass.. √
Appraiser Results can be found: C:\FeatureUpdateBlocks\MJ-MJD82PRJSISQ_20211004_094943\Results.txt
PS C:\Windows\system32> Export-FUBypassBlock -path "c:\temp"
 + Finding and exporting block bypass.. √

This is the upgrade block I am trying to fix (from results.txt):
BlockUpgrade:
Name         Value                                             Ordinal
----         -----                                             -------
SdbAppName   Trend Micro Worry-Free Business Security Services 2      
SdbEntryGuid {de250f35-1cdf-46ba-8882-24d66a5eb66c}            2      
SdbBlockType BlockUpgrade                                      2      
SdbAppGuid   {5f0a8e35-214a-408a-a260-4b61f6fb5089}            2

**Comment by AdamGrossTX** [comment]
Bypass files would export as reg files only if a bypass exists for the particular block. If you don’t have reg files then you can’t bypass the block.
