### ISSUE TITLE
AntiVirus won't let FU.WhyAmIBlocked run

### ISSUE THREAD

**Issue by richsidney** [AdamGrossTX/FU.WhyAmIBlocked#24]
Here is my PowerShell output
`PowerShell 7.2.6
`Copyright (c) Microsoft Corporation.
`
`https://aka.ms/powershell
`Type 'help' to get help.
`
`PS C:\Users\richs> Install-Module FU.WhyAmIBlocked -Scope CurrentUser
`PS C:\Users\richs> Import-Module FU.WhyAmIBlocked
`Write-Error: Failed to import function `C:\Users\richs\OneDrive\Documents\PowerShell\Modules\FU.WhyAmIBlocked\1.0.0.8\Public\ConvertFrom-BinToXML.ps1: At `C:\Users\richs\OneDrive\Documents\PowerShell\Modules\FU.WhyAmIBlocked\1.0.0.8\Public\ConvertFrom-BinToXML.ps1:1 char:1
`+ <#
`+ ~~
`This script contains malicious content and has been blocked by your antivirus software.
`Write-Error: Failed to import function `C:\Users\richs\OneDrive\Documents\PowerShell\Modules\FU.WhyAmIBlocked\1.0.0.8\Public\Expand-SDB.ps1: At `C:\Users\richs\OneDrive\Documents\PowerShell\Modules\FU.WhyAmIBlocked\1.0.0.8\Public\Expand-SDB.ps1:1 char:1
`+
`This script contains malicious content and has been blocked by your antivirus software.
`PS C:\Users\richs>`

Here is the report from my AntiVirus software:
`PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Linx.51.36DA30A5 and was blocked. Your device is safe.

Not sure how to proceed. Please advise

**Comment by AdamGrossTX** [comment]
I haven’t heard of others seeing this issue. Check the code for yourself and you can see what it’s doing and determine whether it’s a false positive or not.
