### ISSUE TITLE
What I need

### ISSUE THREAD

**Issue by kPlusPlus** [AdamGrossTX/FU.WhyAmIBlocked#25]
wrote report.txt
what to do ????

mydearcomputer - 10/06/2022 15:51:00
Found 2 .bin file(s).

    Directory: C:\FeatureUpdateBlocks\KAVIOLINA_20221006_035100\Bin

Mode                 LastWriteTime         Length Name                                                                                                                                                                    
----                 -------------         ------ ----                                                                                                                                                                    
-a----         3.8.2022.      5:23        2451616 AppCompatAppraiser_APPRAISER_TelemetryBaseline_NI22H2.bin                                                                                                               
-a----        6.10.2022.      9:17        2067173 AppCompatAppraiser_APPRAISER_TelemetryBaseline_UNV.bin                                                                                                                  

C:\FeatureUpdateBlocks\KAVIOLINA_20221006_035100\XML\AppCompatAppraiser_APPRAISER_TelemetryBaseline_NI22H2.bin_HUMANREADABLE.XML

Matching GatedBlock....NONE FOUND.
Matching BlockUpgrade....FOUND!
BlockUpgrade:
============

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   VMware Workstation Pro                 2      
SdbEntryGuid {4b9bb66d-2725-4274-b331-54a1950c6b8a} 2      
SdbBlockType BlockUpgrade                           2      
SdbAppGuid   {7ebb75d7-6f34-42fb-8468-162a6c4f70c3} 2      

All SDB Entries For: C:\FeatureUpdateBlocks
For: C:\FeatureUpdateBlocks
Entry 0 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   BattlEye Anticheat                     2      
SdbEntryGuid {3f6b2bc0-2675-4416-82e8-89943adc24b6} 2      
SdbBlockType ApphelpHardBlock                       2      
SdbAppGuid   {24260bae-f74b-4ce0-b2b4-3335da5c63d4} 2      

Entry 1 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   Microsoft Office                       2      
SdbEntryGuid {fe2a6f06-be2c-4ece-a9a6-b6a4f635b129} 2      
SdbAppGuid   {38feba87-6d1f-496a-bf6b-ad0b622807cd} 2      

Entry 2 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   Microsoft Office                       2      
SdbEntryGuid {6d94f994-e6ae-4f1c-b286-61d63872c3db} 2      
SdbAppGuid   {38feba87-6d1f-496a-bf6b-ad0b622807cd} 2      

Entry 3 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   Microsoft Office                       2      
SdbEntryGuid {27398951-0ddc-413f-8ca5-aa8bb300c1a4} 2      
SdbAppGuid   {38feba87-6d1f-496a-bf6b-ad0b622807cd} 2      

Entry 4 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   Microsoft Office                       2      
SdbEntryGuid {3ee1a465-60ad-43f2-b1bb-be6e5cf99cd3} 2      
SdbAppGuid   {38feba87-6d1f-496a-bf6b-ad0b622807cd} 2      

Entry 5 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   Microsoft Office                       2      
SdbAppName   Microsoft Office                       3      
SdbEntryGuid {44beb94e-be85-4e88-b9fa-c328358e860b} 2      
SdbEntryGuid {00ae5524-e38d-42b5-818c-ee370ecd3484} 3      
SdbAppGuid   {38feba87-6d1f-496a-bf6b-ad0b622807cd} 2      
SdbAppGuid   {38feba87-6d1f-496a-bf6b-ad0b622807cd} 3      

Entry 6 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          3      
SdbAppName       VMware Workstation Pro                 2      
SdbAppName       VMware Workstation Pro                 4      
SdbAppName       __P0__ VMware Workstation Pro (No-Op)  3      
SdbEntryGuid     {4b9bb66d-2725-4274-b331-54a1950c6b8a} 2      
SdbEntryGuid     {47d17d36-ec23-4f12-813a-7257ce075443} 3      
SdbEntryGuid     {66f21bbc-149a-411b-8e11-880af7c1266c} 4      
SdbBlockType     BlockUpgrade                           2      
SdbBlockType     ApphelpSoftBlock                       4      
SdbAppGuid       {7ebb75d7-6f34-42fb-8468-162a6c4f70c3} 2      
SdbAppGuid       {257bb53b-2403-49c0-adb8-27c5d512de01} 3      
SdbAppGuid       {7ebb75d7-6f34-42fb-8468-162a6c4f70c3} 4      

Entry 7 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   Microsoft Office                       2      
SdbEntryGuid {8023de0f-0909-4d2a-b36a-8d2fc7de7465} 2      
SdbAppGuid   {38feba87-6d1f-496a-bf6b-ad0b622807cd} 2      

Entry 8 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   VC Runtime                             1      
SdbEntryGuid {00b0c9b2-3f04-4795-a8ac-5b7bd5ea2ea8} 1      
SdbAppGuid   {03760bce-35d7-47a3-b83b-de673fdb6ab4} 1      

Entry 9 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          2      
SdbAppName       __P0__ No-Op Market Share              2      
SdbEntryGuid     {414c4ccb-8364-4037-9b10-3570049ca91b} 2      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 2      

Entry 10 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          3      
SdbAppName       __P0__ No-Op Market Share              3      
SdbEntryGuid     {69997fb5-bfc0-4c4c-bb42-18aae2f79d49} 3      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 3      

Entry 11 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          4      
SdbAppName       __P0__ No-Op Market Share              4      
SdbEntryGuid     {1be0c418-68f8-4ed9-9020-41bac0ab27b1} 4      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 4      

Entry 12 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          5      
SdbAppName       __P0__ No-Op Market Share              5      
SdbEntryGuid     {4dac7c1a-1692-46d5-9e01-bcc3405aea42} 5      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 5      

Entry 13 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          6      
SdbAppName       __P0__ No-Op Market Share              6      
SdbEntryGuid     {80976924-e397-4385-865c-20b51fbb4d85} 6      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 6      

Entry 14 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          7      
SdbAppName       __P0__ No-Op Market Share              7      
SdbEntryGuid     {5a5ca179-84f7-4c60-8d20-b7e4a98ccde2} 7      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 7      

Entry 15 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          8      
SdbAppName       __P0__ No-Op Market Share              8      
SdbEntryGuid     {ec0a42c4-6d39-40c3-8190-296f37d269c5} 8      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 8      

Entry 16 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          9      
SdbAppName       __P0__ No-Op Market Share              9      
SdbEntryGuid     {6cf87ca8-d96e-4b68-95ba-aa20229d51aa} 9      
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 9      

Entry 17 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          10     
SdbAppName       __P0__ No-Op Market Share              10     
SdbEntryGuid     {d8bfb02a-340a-4f5b-97f5-31624cf9adae} 10     
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 10     

Entry 18 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          11     
SdbAppName       __P0__ No-Op Market Share              11     
SdbEntryGuid     {eacdca70-886f-4e01-9331-92b9609b7b83} 11     
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 11     

Entry 19 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          12     
SdbAppName       __P0__ No-Op Market Share              12     
SdbEntryGuid     {c3323135-d1bd-4c6c-8498-29d452fd0b5a} 12     
SdbAppGuid       {e90e4301-4eed-4786-b0a7-a46d21ce0fce} 12     

Entry 20 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          13     
SdbAppName       __P0__ [AV Health] Avast Antivirus     13     
SdbEntryGuid     {623fed2f-7af2-489d-afdf-1337381a306d} 13     
SdbAppGuid       {9d9be83e-7d7a-421b-9b12-928f7194812f} 13     

Entry 21 : 

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData TelemetryOnly                          14     
SdbAppName       __P0__ [AV Health] Avast Antivirus     14     
SdbEntryGuid     {efa677e8-2f2d-4833-a5b1-0d8bd7e1da04} 14     
SdbAppGuid       {9d9be83e-7d7a-421b-9b12-928f7194812f} 14     

Entry 22 : 

Name             Value                                         Ordinal
----             -----                                         -------
SdbAppraiserData TelemetryOnly                                 15     
SdbAppName       __P0__ [AV Health] Trend Micro Security Agent 15     
SdbEntryGuid     {467735e2-f95a-4c9a-9a13-f303bdfd4e14}        15     
SdbAppGuid       {f030eda4-77cd-498a-9d1b-8307e5741185}        15     

Entry 23 : 

Name             Value                                         Ordinal
----             -----                                         -------
SdbAppraiserData TelemetryOnly                                 16     
SdbAppName       __P0__ [AV Health] Trend Micro Security Agent 16     
SdbEntryGuid     {218177cc-b09b-4e34-ba11-1943f8573cd5}        16     
SdbAppGuid       {f030eda4-77cd-498a-9d1b-8307e5741185}        16     

Entry 24 : 

Name         Value                                  Ordinal
----         -----                                  -------
SdbAppName   Migrate Appraiser Markers              17     
SdbEntryGuid {3b262b50-25ce-4ad9-8aad-0cf9e3d134c6} 17     
SdbAppGuid   {3cd1024d-65c0-4c5f-96c9-80bbcf1e9d8b} 17     

C:\FeatureUpdateBlocks\KAVIOLINA_20221006_035100\XML\AppCompatAppraiser_APPRAISER_TelemetryBaseline_UNV.bin_HUMANREADABLE.XML

Matching GatedBlock....NONE FOUND.
Matching Block Upgrade....NONE FOUND.
All SDB Entries For: C:\FeatureUpdateBlocks
For: C:\FeatureUpdateBlocks
AppCompat Registry Flags
==============
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Appraiser
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Appraiser\SEC
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Appraiser\GWX

**Comment by mib1982** [comment]
While this is not an bug per se, I agree with the OPs desire to have help or instructions on how to interpret the results.

**Comment by AdamGrossTX** [comment]
Have you read the blog that goes along with this module? Also, the module is 2 yrs old and I haven't really spent any time on it since releasing it. It may need a bit of TLC.

https://www.asquaredozen.com/2020/07/26/demystifying-windows-10-feature-update-blocks/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mib1982** [comment]
No, as a matter of fact I have not.  I read about your script on [Computerworld.](https://www.computerworld.com/article/3675334/windows-11-22h2-is-out-so-why-isnt-your-pc-getting-it.html) Thank you for pointing me to that original blog post.

Also, I overlooked the penultimate line of the script's output and only paid attention to the last line.
```
 + No blocks Found. Congratulations!!.. √
Appraiser Results can be found: C:\FeatureUpdateBlocks\DESKTOP-PC_20221006_072830\Results.txt
```

Now everything is clear for me. Thanks again.

**Comment by ante2103** [comment]
I'm also getting "No blocks found" and I still don't have windows 11 22h2 update
any clue why it's not available for me yet
