### ISSUE TITLE
'ConvertFrom-FUBinToXML' is not recognized

### ISSUE THREAD

**Issue by tagatac** [AdamGrossTX/FU.WhyAmIBlocked#32]
When I run `Get-FUBlocks`, I get the following error:
```
PS C:\Users\tag> Get-FUBlocks
 + Creating Output Folders .. √
 + Getting .source files..
 ++ copying C:\Windows\appcompat\appraiser\APPRAISER_TelemetryBaseline_UNV.bin to C:\FeatureUpdateBlocks\PC_20221025_024930\Bin√
 ++ copying C:\Windows\System32\appraiser\appraiser.sdb to C:\FeatureUpdateBlocks\PC_20221025_024930\AppraiserData\System32Appraiser√
 ++ copying C:\Windows\System32\appraiser\Appraiser_Data.ini to C:\FeatureUpdateBlocks\PC_20221025_024930\AppraiserData\System32Appraiser√
WARNING: The term 'ConvertFrom-FUBinToXML' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ConvertFrom-FUBinToXML : The term 'ConvertFrom-FUBinToXML' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\tag\Google Drive\WindowsPowerShell\Modules\FU.WhyAmIBlocked\1.0.0.9\Public\Get-FUBlocks.ps1:166 char:13
+             ConvertFrom-FUBinToXML -FileList $BinFiles -OutputPath $X ...
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ConvertFrom-FUBinToXML:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

OS: Windows 11 Pro 21H2 build 22000.1098

**Comment by AdamGrossTX** [comment]
Try installing the module from the Powershell gallery.

Install-Module FU.WhyAmIBlocked -Force

Adam Gross
A Square Dozen
Blogger-In-Chief
Twitter: AdamGrossTX
http://www.asquaredozen.com
________________________________
From: David Tagatac ***@***.***>
Sent: Tuesday, October 25, 2022 4:44:02 PM
To: AdamGrossTX/FU.WhyAmIBlocked ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AdamGrossTX/FU.WhyAmIBlocked] 'ConvertFrom-FUBinToXML' is not recognized (Issue #32)


When I run Get-FUBlocks, I get the following error:

PS C:\Users\tag> Get-FUBlocks

 + Creating Output Folders .. √

 + Getting .source files..

 ++ copying C:\Windows\appcompat\appraiser\APPRAISER_TelemetryBaseline_UNV.bin to C:\FeatureUpdateBlocks\PC_20221025_024930\Bin√

 ++ copying C:\Windows\System32\appraiser\appraiser.sdb to C:\FeatureUpdateBlocks\PC_20221025_024930\AppraiserData\System32Appraiser√

 ++ copying C:\Windows\System32\appraiser\Appraiser_Data.ini to C:\FeatureUpdateBlocks\PC_20221025_024930\AppraiserData\System32Appraiser√

WARNING: The term 'ConvertFrom-FUBinToXML' is not recognized as the name of a cmdlet, function, script file, or operable

program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

ConvertFrom-FUBinToXML : The term 'ConvertFrom-FUBinToXML' is not recognized as the name of a cmdlet, function, script file,

or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

At C:\Users\tag\Google Drive\WindowsPowerShell\Modules\FU.WhyAmIBlocked\1.0.0.9\Public\Get-FUBlocks.ps1:166 char:13

+             ConvertFrom-FUBinToXML -FileList $BinFiles -OutputPath $X ...

+             ~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (ConvertFrom-FUBinToXML:String) [], ParentContainsErrorRecordException

    + FullyQualifiedErrorId : CommandNotFoundException



OS: Windows 11 Pro 21H2 build 22000.1098

**Comment by tagatac** [comment]
That was how I installed it.
```
PS C:\Users\tag> Install-Module -Name FU.WhyAmIBlocked -Scope CurrentUser

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value
 by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PS C:\Users\tag> Import-Module FU.WhyAmIBlocked
PS C:\Users\tag> Get-FUBlocks
```

**Comment by tagatac** [comment]
It turns out Bitdefender was blocking it:
```
Suspicious activity blocked
6 minutes ago

Feature:
Antivirus

PowerShell tried to load a malicious resource detected as Heur.BZC.ZFV.Boxter.811.58D3FC63 and was blocked. Your device is safe.
```
After temporarily disabling Bitdefender antivirus, the module ran as advertised.

No blocks found, though, so my confusion about not getting 22H2 continues...
