### ISSUE TITLE
Python detection fails for 2.7.16

### ISSUE THREAD

**Issue by VirtualTim** [AdamGrossTX/FU.WhyAmIBlocked#4]
Running `Import-Module FU.WhyAmIBlocked` displays:
```
Python 2.7.16
Import-Module : Python is not installed. Install Pyton before proceeding.
At line:1 char:1
+ Import-Module FU.WhyAmIBlocked
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Python is not i...ore proceeding.:String) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : Python is not installed. Install Pyton before proceeding.,Microsoft.PowerShell.Commands.ImportModuleCommand
```

I believe this is because (some?) Python 2 versions output `python --version`  to err instead of out.

Using this as the check should work for this version:
`$PythonVersion = "$(python --version 2>&1)"`

**Comment by AdamGrossTX** [comment]
That's a good catch. I have only tested with Python 3.8 and this is my first time using Python. I'll do some tests with the next release to handle this. Thank you!

Also, I just added the ability to specify a path to Python if you want to use a portable python. 

Oh I also tested with Python from the Windows Store and that works as well.

**Comment by AdamGrossTX** [comment]
The latest release has an option to update c:\FeatureUpdateBlocks\fuconfig.json manually to set the PythonPath to the folder where python.exe is. If you have python in your environment variable, it should use that automatically.

**Comment by VirtualTim** [comment]
I still was unable to run `Import-Module FU.WhyAmIBlocked`. I had to change this:
https://github.com/AdamGrossTX/FU.WhyAmIBlocked/blob/411dcbfc7eb38809b381a7b6dddd825de896c6e0/Build.ps1#L137-L142

To this (I edited the psm1, so I didn't need the backticks):
``` `$PythonVersion = `"`$(python --version 2>&1)`"```

And then everything worked.

**Comment by AdamGrossTX** [comment]
I just tested again on a machine with no Python and got your original message so it looks like there's an issue still. I'll try out your code. Thanks!~

**Comment by AdamGrossTX** [comment]
@VirtualTim this should be in 1.0.0.6 on the powershell gallery. Can you please re-test?

**Comment by VirtualTim** [comment]
Using 1.0.0.6: Running `Import-Module FU.WhyAmIBlocked` I now get:
```
Python 2.7.16
Python 2.7.16
WARNING: Python is not installed. Install Python then re-import the module then run 'Initialize-FUModule -Reset'.
        You may need to close PowerShell and re-launch after install.
 + You can install the Windows Store version from here https://www.microsoft.com/store/productId/9MSSZTT1N39L
```

**Comment by AdamGrossTX** [comment]
Well dang. I'll give it another go. Sorry and thanks for testing.

**Comment by VirtualTim** [comment]
No worries. I've managed to work around it myself, but I'm happy to test builds for you.

**Comment by AdamGrossTX** [comment]
Please run build.ps1 on the repo and test locally. Then I will push to the gallery.

**Comment by VirtualTim** [comment]
That seems to have fixed it. 👍

**Comment by AdamGrossTX** [comment]
@VirtualTim after all of this - I finally got the code working to remove the Python dependency altogether. Can you build and test the dev branch and see if it still works as expected? It still needs some file checks and cleanup but I think it's 95% there.

https://github.com/AdamGrossTX/FU.WhyAmIBlocked/tree/Dev

**Comment by VirtualTim** [comment]
Yep, it all works well for me. Latest commit when I pulled down was cdc949b.
