### ISSUE TITLE
No Match.txt is created

### ISSUE THREAD

**Issue by PathogenDavid** [AdamGrossTX/FU.WhyAmIBlocked#6]
After running `Get-FUBlocks` (version 1.0.0.3) it states "Appraiser Database matches can be found: C:\FeatureUpdateBlocks\LOVELACE\Match.txt"

Unfortunately, this file does not exist. If I inspect Results.txt, I can see it's being blocked by "Windows Searchbox":

```
Matching GatedBlock....FOUND!
GatedBlock:
==========

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData GatedBlock                             3      
SdbAppName       Windows Searchbox                      3      
SdbEntryGuid     {5e757e51-cc84-4a4a-ae70-d69a6a2b37f1} 3      
SdbAppGuid       {1b07f560-9ebf-461e-a71b-f3b2c7af46af} 3      
```

Not sure if it matters, but the `tmp\AllMatches.json` file is basically empty:

```json
{

}
```

While waiting for #2 to be solved, I tried manually looking up this entry in the SDB manually as [suggested by your comment here](https://github.com/AdamGrossTX/FU.WhyAmIBlocked/issues/2#issuecomment-664793403) and found no matching entry. At the time I assumed I was doing something wrong, but now I'm wondering if this block is just weird.

**Comment by PathogenDavid** [comment]
The same thing happened on my laptop (with a different entry this time):

```
Matching GatedBlock....FOUND!
GatedBlock:
==========

Name             Value                                  Ordinal
----             -----                                  -------
SdbAppraiserData GatedBlock                             1      
SdbAppName       DX9 games + VRR panel                  1      
SdbEntryGuid     {fa1d81f1-57b7-4907-970a-a37d80d41304} 1      
SdbAppGuid       {af974e9d-1e00-48c6-9662-6313f4683408} 1     
```

**Comment by AdamGrossTX** [comment]
Interesting. Can you upload your bin file and appraiser_alrernatedata.cab and I'll see if I can sort it out. "It worked on my machine!" Lol.

**Comment by PathogenDavid** [comment]
Here you go: _&lt;Link deleted&gt;_

I included both machines in the zip. I just copied the folders out of `C:\FeatureUpdateBlocks` and grabbed `Appraiser_AlternateData.cab` from `C:\Windows\appcompat\appraiser\`. I'm assuming the bin files in the `tmp` folder are what you were referring to.

It's also maybe worth mentioning that both machines are running Python 3.8.5 (amd64)

**Comment by AdamGrossTX** [comment]
@PathogenDavid  Can you please run 

.\Build.ps1 -ModulePath .\FU.WhyAmIBlocked -Build Local

and then test again on those devices? I made a bunch of changes to handle files from various locations and handle multiple files. 

Basically, I wasn't handling multiple sdb's properly.

**Comment by PathogenDavid** [comment]
Working now, thanks a lot!

I was only able to run it on one of them (I was able to guess based on the name for the other one and it's on 2004 now.)

Just in case it's not expected: I did have to install PowerShell 7 (to run `Build.ps1`) and run as administrator to get things working.

**Comment by PathogenDavid** [comment]
I was able to confirm with the still-blocked machine that `5e757e51-cc84-4a4a-ae70-d69a6a2b37f1` works with `Find-FUBlocksInSDB`, so I assume if I hadn't fixed the issue on the now-2004 machine it'd have worked there too.

Thanks again! I've wished for better insight into feature update blocks for a long time so I can make informed decisions on whether they actually matter to me. (Like in this case where my display panel is apparently VRR capable but considering my GPU isn't...not really a block I care about.)

**Comment by AdamGrossTX** [comment]
1.0.0.4 published to the gallery. Should be good to go.
