### ISSUE TITLE
Mix of UTF-16 and UTF8 in Results.txt

### ISSUE THREAD

**Issue by gbloice** [AdamGrossTX/FU.WhyAmIBlocked#9]
The portions of Results.txt that are written by Get-BlocksFromBin using Out-File are encoded as UTF16 as that's the default encoding of the cmdlet, whereas the other text written by Add-Content is the encoding of the source file which is UTF8.

This can be fixed by adding an `-Encoding UTF8` argument to all uses of Out-File.

**Comment by AdamGrossTX** [comment]
Thank you for this tip. I'll get it fixed.  I have seen this bug only a few times and thought it was something random.
